name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "00 00 * * *"
    - cron: "00 02 * * *"
    - cron: "00 04 * * *"
    - cron: "00 06 * * *"
    - cron: "00 08 * * *"
    - cron: "00 10 * * *"
    - cron: "00 12 * * *"
    - cron: "00 14 * * *"
    - cron: "00 16 * * *"
    - cron: "00 18 * * *"
    - cron: "00 20 * * *"
    - cron: "00 22 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run update-readme
    - run: |
        cat /etc/os-release
        date
        git config user.name hulkike
        git config user.email hulkike@gmail.com
        git add .
        git commit -m "[bot] Update README"
        git push origin main

